version: "3.7"

services:
  app:
    image: demo-maven:development
    ports:
      - ${DEMO_WEB_PORT:-8080}
    build:
      context: .
      target: development
    command: mvn spring-boot:run
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo_development
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3x4mpl3P455w0rd
      PORT: ${DEMO_WEB_PORT:-8080}